// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX8ckQOUzk7cPyTSi7Zcv-XVa79rOnNVE',
    appId: '1:622778374424:web:0ea343319a45714cf1e66d',
    messagingSenderId: '622778374424',
    projectId: 'infinite-d16fc',
    authDomain: 'infinite-d16fc.firebaseapp.com',
    storageBucket: 'infinite-d16fc.appspot.com',
    measurementId: 'G-LSZ01KWX2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt-8n73kA85C8HnhDrAOHCC1okK4J6evg',
    appId: '1:622778374424:android:bcd344bad4cbfdb4f1e66d',
    messagingSenderId: '622778374424',
    projectId: 'infinite-d16fc',
    storageBucket: 'infinite-d16fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4As7a-YXAdXwfUcRP8LeLWZ_6H7Ls0rc',
    appId: '1:622778374424:ios:7fe1f5e7a1913882f1e66d',
    messagingSenderId: '622778374424',
    projectId: 'infinite-d16fc',
    storageBucket: 'infinite-d16fc.appspot.com',
    iosClientId: '622778374424-o7fs0umr5d2rj2qk1ivqfc630eithbpq.apps.googleusercontent.com',
    iosBundleId: 'com.infinite.infinite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4As7a-YXAdXwfUcRP8LeLWZ_6H7Ls0rc',
    appId: '1:622778374424:ios:7fe1f5e7a1913882f1e66d',
    messagingSenderId: '622778374424',
    projectId: 'infinite-d16fc',
    storageBucket: 'infinite-d16fc.appspot.com',
    iosClientId: '622778374424-o7fs0umr5d2rj2qk1ivqfc630eithbpq.apps.googleusercontent.com',
    iosBundleId: 'com.infinite.infinite',
  );
}
